### ISSUE TITLE
"Cancel" Button for Rides

### ISSUE THREAD

**Issue by aliceduongg** [aliceduongg/StuberProject#18]
@JoePan001 
When a rider posts a ride or a driver accepts a ride, that ride is added to their respective ride lists. If, on the scheduled day, either the rider or driver cannot make it, they should have the option to cancel the ride.
Tasks:
- Cancel Button: Add a "Cancel" button for each ride listed in both the rider's and driver's ride lists.
- Functionality: When the "Cancel" button is clicked, the corresponding ride should be removed from the list of that rider or driver.
- UI/UX: Ensure the "Cancel" button is visible and easily accessible next to each ride entry.

**Comment by aliceduongg** [comment]
@aliceduongg After button is implemented, Alice will handle email notification which will be sent to both rider and driver who being impact by that 'cancel' action .

**Comment by JoePan001** [comment]
The logic looks fine. The console shows that the correct rideID has been called for all users. However, the riders get 401 unauthorized and the drivers got 400 bad request.
